### ISSUE TITLE
losetup -D

### ISSUE THREAD

**Issue by AddoSolutions** [Ezka77/xen-orchestra-ce#1]
Hello,

I am unable to get this to work because busybox does not support `losetup -D`.

Code reference: https://github.com/vatesfr/xo-server/blob/68a94da44c0d3fba33e3ba9d5159618d19170e48/src/xo-mixins/backups.js#L313

How are people getting around this error?

```
# docker-compose up
Starting xoa-redis
Starting xoa
Attaching to xoa-redis, xoa
xoa-redis    | 1:C 17 Aug 17:16:42.955 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
xoa-redis    | 1:C 17 Aug 17:16:42.955 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
xoa-redis    | 1:C 17 Aug 17:16:42.955 # Configuration loaded
xoa-redis    | 1:M 17 Aug 17:16:42.958 * Running mode=standalone, port=6379.
xoa-redis    | 1:M 17 Aug 17:16:42.958 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
xoa-redis    | 1:M 17 Aug 17:16:42.958 # Server initialized
xoa-redis    | 1:M 17 Aug 17:16:42.958 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
xoa-redis    | 1:M 17 Aug 17:16:42.958 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
xoa-redis    | 1:M 17 Aug 17:16:42.959 * DB loaded from append only file: 0.000 seconds
xoa-redis    | 1:M 17 Aug 17:16:42.959 * Ready to accept connections
xoa          | yarn start v0.24.4
xoa          | $ node bin/xo-server
xoa          | Thu, 17 Aug 2017 17:16:46 GMT xo:main Configuration loaded.
xoa          | Thu, 17 Aug 2017 17:16:46 GMT xo:main Web server listening on http://[::]:80
xoa          | Thu, 17 Aug 2017 17:16:46 GMT xo:main User changed to node
xoa          | [WARN] start error: Error: Command failed: losetup -D
xoa          | losetup: unrecognized option: D
xoa          | BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.
xoa          |
xoa          | Usage: losetup [-r] [-o OFS] {-f|LOOPDEV} FILE - associate loop devices
xoa          | 	losetup -d LOOPDEV - disassociate
xoa          | 	losetup -a - show status
xoa          | 	losetup -f - show next free loop device
xoa          |
xoa          | 	-o OFS	Start OFS bytes into FILE
xoa          | 	-r	Read-only
xoa          | 	-f	Show/use next free loop device
xoa          |
xoa          |
xoa          |     at Promise.all.then.arr (/home/node/xo-server/node_modules/execa/index.js:231:11)
xoa          |     at tryCatcher (/home/node/xo-server/node_modules/bluebird/js/release/util.js:16:23)
xoa          |     at Promise._settlePromiseFromHandler (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:512:31)
xoa          |     at Promise._settlePromise (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:569:18)
xoa          |     at Promise._settlePromise0 (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
xoa          |     at Promise._settlePromises (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
xoa          |     at Promise._fulfill (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:638:18)
xoa          |     at PromiseArray._resolve (/home/node/xo-server/node_modules/bluebird/js/release/promise_array.js:126:19)
xoa          |     at PromiseArray._promiseFulfilled (/home/node/xo-server/node_modules/bluebird/js/release/promise_array.js:144:14)
xoa          |     at Promise._settlePromise (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:574:26)
xoa          |     at Promise._settlePromise0 (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
xoa          |     at Promise._settlePromises (/home/node/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
xoa          |     at Async._drainQueue (/home/node/xo-server/node_modules/bluebird/js/release/async.js:133:16)
xoa          |     at Async._drainQueues (/home/node/xo-server/node_modules/bluebird/js/release/async.js:143:10)
xoa          |     at Immediate.Async.drainQueues (/home/node/xo-server/node_modules/bluebird/js/release/async.js:17:14)
xoa          |     at runCallback (timers.js:672:20)
xoa          |     at tryOnImmediate (timers.js:645:5)
xoa          |     at processImmediate [as _immediateCallback] (timers.js:617:5)
xoa          | Warning: connect.session() MemoryStore is not
xoa          | designed for a production environment, as it will leak
xoa          | memory, and will not scale past a single process.
xoa          | Thu, 17 Aug 2017 17:16:47 GMT xo:main Setting up / → /home/node/xo-web/dist/
```

Nick

**Comment by Ezka77** [comment]
Hi,

```
xoa          | [WARN] start error: Error: Command failed: losetup -D
```
It's just a Warning, XOA should work. Besides, by reading the last log line you provide, I think the start process is still going on.

I'm not a XOA dev, but this piece of code is about LVM ... wich is NOT in this docker container. So no matter `losetup` : `vgchange` or `pvscan` will fail too.

**Comment by AddoSolutions** [comment]
You are correct, I thought it was unable to run the setup script because it didnt give me a default username/password to work with.  

If I recall the default username and password is:

admin@admin.co
admin

For those who may be googling this and like me were unable to find it.  Doh!
