### ISSUE TITLE
When importing VMs or disks, the task stops about 1 minute later

### ISSUE THREAD

**Issue by xbb** [Ezka77/xen-orchestra-ce#39]
Hello, I'm testing XCP-ng for the first time.

When trying to import a 2GB vmdk file (or an .ova export) the task stops at about 48% (about 1 minute since started)

With another container image I didn't have this issue, neither with the official XOA vm.

I've rebuilt the image using node 14.16 (and 14.15.1-5) as runtime (using the same built code with 14.5.0 to speed up the process) and it seems I have no issue importing the disk/VM now.

The official VM image (stable branch) uses node 14.15.4 at the moment.

This is the diff of the Dockerfile I used for testing:

```diff
--- ../alpine/Dockerfile        2021-03-14 12:53:46.143993193 +0100
+++ Dockerfile  2021-03-14 14:24:13.414351211 +0100
@@ -40,6 +40,8 @@
     make && \
     make install

+FROM node:14.15.4-alpine3.12 as node-runtime
+
 # Runner container
 FROM alpine:3.12

@@ -76,8 +78,8 @@

 # Only copy over the node pieces we need from the above image
 #fix node - new path - version 14.5
-COPY --from=build /usr/local/bin/node /usr/bin/
-COPY --from=build /usr/lib/libgcc* /usr/lib/libstdc* /usr/lib/
+COPY --from=node-runtime /usr/local/bin/node /usr/bin/
+COPY --from=node-runtime /usr/lib/libgcc* /usr/lib/libstdc* /usr/lib/

 # Get libvhdi
 COPY --from=build-libvhdi /usr/local/bin/vhdimount /usr/local/bin/vhdiinfo  /usr/local/bin/
```

For reference this is the error that is logged when using node 14.5.0

```
2021-03-14T13:31:09.121Z xo:xo-server ERROR unhandled error event {
  error: Error: Request aborted
      at IncomingMessage.onReqAborted (/home/node/xen-orchestra/node_modules/multiparty/index.js:195:17)
      at IncomingMessage.apply (events.js:314:20)
      at IncomingMessage.patchedEmit (/home/node/xen-orchestra/@xen-orchestra/log/src/configure.js:92:17)
      at IncomingMessage.EventEmitter.emit (domain.js:486:12)
      at abortIncoming (_http_server.js:535:9)
      at socketOnClose (_http_server.js:528:3)
      at Socket.apply (events.js:326:22)
      at Socket.patchedEmit (/home/node/xen-orchestra/@xen-orchestra/log/src/configure.js:92:17)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at TCP.<anonymous> (net.js:673:12)
}
2021-03-14T13:31:09.140Z xo:xo ERROR HTTP request error {
  error: Error: Request aborted
      at IncomingMessage.onReqAborted (/home/node/xen-orchestra/node_modules/multiparty/index.js:195:17)
      at IncomingMessage.apply (events.js:314:20)
      at IncomingMessage.patchedEmit (/home/node/xen-orchestra/@xen-orchestra/log/src/configure.js:92:17)
      at IncomingMessage.EventEmitter.emit (domain.js:486:12)
      at abortIncoming (_http_server.js:535:9)
      at socketOnClose (_http_server.js:528:3)
      at Socket.apply (events.js:326:22)
      at Socket.patchedEmit (/home/node/xen-orchestra/@xen-orchestra/log/src/configure.js:92:17)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at TCP.<anonymous> (net.js:673:12)
}
```

**Comment by Ezka77** [comment]
Hi xbb !

Indeed I should upgrade the build container, I think it will solve this error.

**Comment by Ezka77** [comment]
I've push a patch and build a new docker image. Let me know if it fixes your issue. It uses node-14.15 to build the image and to run XOA in the container.

**Comment by xbb** [comment]
Yes, it does fix it.
Sorry it took me a while because I replaced XCP-ng with Proxmox in my homelab server.
Tested both the previous and current image with XCP-ng running in a VM, the new version fixes the issue.
Thanks!

**Comment by Ezka77** [comment]
Great ! Thanks for doing the tests.
