### ISSUE TITLE
assign allowed ip address to vm network not working

### ISSUE THREAD

**Issue by christianuhlmann** [Ezka77/xen-orchestra-ce#4]
hi
i use the latest build with xo-server & xo-web 5.17.1 and i can not assign the allowed ip adresses to the network interface from the vm.
the previous version has the same error

after starting a fresh image i get these docker error:

>  yarn run v1.5.1
 $ node bin/xo-server
 2018-03-11T19:09:04.112Z xo:main Configuration loaded.
 2018-03-11T19:09:04.117Z xo:main Web server listening on http://[::]:8000
 [WARN] hook start failure: Error: Command failed: vgchange -an
   WARNING: Running as a non-root user. Functionality may be unavailable.
   /run/lock: mkdir failed: Permission denied
   Failed to create directory /run/lock/lvm.
   File-based locking initialisation failed.
     at makeError (/home/node/xen-orchestra/packages/xo-server/node_modules/execa/index.js:169:9)
     at Promise.all.then.arr (/home/node/xen-orchestra/packages/xo-server/node_modules/execa/index.js:274:16)
     at run (/home/node/xen-orchestra/node_modules/core-js/modules/es6.promise.js:66:22)
     at /home/node/xen-orchestra/node_modules/core-js/modules/es6.promise.js:79:30
     at flush (/home/node/xen-orchestra/node_modules/core-js/modules/_microtask.js:18:9)
     at _combinedTickCallback (internal/process/next_tick.js:73:7)
     at process._tickCallback (internal/process/next_tick.js:104:9)
 Warning: connect.session() MemoryStore is not
 designed for a production environment, as it will leak
 memory, and will not scale past a single process.
 2018-03-11T19:09:04.342Z xo:main Setting up / → /home/node/xen-orchestra/packages/xo-web/dist/
 2018-03-11T19:09:05.663Z xo:main + WebSocket connection (::ffff:192.168.127.12)

do you get the same error?
can you assign an ip adress to an network interface for an vm?

can i see more logs than these: 
`docker container logs XO_server --details -f`

thanks christian

**Comment by christianuhlmann** [comment]
ok
i have checked this issue with a normal version from source on a fresh debian stretch system as mentioned here: https://xen-orchestra.com/docs/from_the_sources.html
there i get the same error.
Anyway, do you have any idea what that might be?

**Comment by Ezka77** [comment]
Hi,
theses are just Warnings: in the container XO cannot use root privileged commant like `vgchange`. The `XOSAN` may not work but it's disabled for the community edition. I don't know why they keep this test here anyway.

I've never used the `Allowed Ip's` functionnality, seems to lock the network IP range for a VM. If the VM use an IP outside the allowed ones it should not have network connection. But I think you should be able to assign any IP you want to your VM network interface from your VM's OS.

**Comment by christianuhlmann** [comment]
no docker image issue
