### ISSUE TITLE
Warnings on Xen Orcheshtra Logs on Startup

### ISSUE THREAD

**Issue by gb-123-git** [Ezka77/xen-orchestra-ce#68]
@Ezka77 
I don't know whether this is on Orchestra side or due to Remco. If this does not belong here, then let me know, I'll post it to Orchestra GitHub:

```
2024-10-21T07:03:40.880Z xo:mixins:hooks WARN start failure {
orchestra-1  |   error: Error: spawn xenstore-read ENOENT
orchestra-1  |       at Process.ChildProcess._handle.onexit (node:internal/child_process:284:19)
orchestra-1  |       at onErrorNT (node:internal/child_process:477:16)
orchestra-1  |       at processTicksAndRejections (node:internal/process/task_queues:82:21) {
orchestra-1  |     errno: -2,
orchestra-1  |     code: 'ENOENT',
orchestra-1  |     syscall: 'spawn xenstore-read',
orchestra-1  |     path: 'xenstore-read',
orchestra-1  |     spawnargs: [ 'vm' ],
orchestra-1  |     cmd: 'xenstore-read vm'
orchestra-1  |   }
orchestra-1  | }
orchestra-1  | 2024-10-21T07:03:45.847Z xo:mixins:hooks WARN start anonymous listener is still running {
orchestra-1  |   source: 'async () => {\n' +
orchestra-1  |     "      await Promise.all([execa('losetup', ['-D']), execa('vgchange', ['-an'])]);\n" +
orchestra-1  |     "      await execa('pvscan', ['--cache']);\n" +
orchestra-1  |     '    }'
orchestra-1  | }
orchestra-1  | 2024-10-21T07:03:45.902Z xo:mixins:hooks WARN start failure {
orchestra-1  |   error: Error: Command failed with exit code 5: vgchange -an
orchestra-1  |   File descriptor 102 (/dev/urandom) leaked on vgchange invocation. Parent PID 17: node
orchestra-1  |     Logical volume vg0/lv_swap in use.
orchestra-1  |     Can't deactivate volume group "vg0" with 2 open logical volume(s)
orchestra-1  |       at makeError (file:///home/node/xen-orchestra/packages/xo-server/node_modules/execa/lib/error.js:60:11)
orchestra-1  |       at handlePromise (file:///home/node/xen-orchestra/packages/xo-server/node_modules/execa/index.js:124:26) {
orchestra-1  |     shortMessage: 'Command failed with exit code 5: vgchange -an',
orchestra-1  |     command: 'vgchange -an',
orchestra-1  |     escapedCommand: 'vgchange -an',
orchestra-1  |     exitCode: 5,
orchestra-1  |     signal: undefined,
orchestra-1  |     signalDescription: undefined,
orchestra-1  |     stdout: '',
orchestra-1  |     stderr: 'File descriptor 102 (/dev/urandom) leaked on vgchange invocation. Parent PID 17: node\n' +
orchestra-1  |       '  Logical volume vg0/lv_swap in use.\n' +
orchestra-1  |       `  Can't deactivate volume group "vg0" with 2 open logical volume(s)`,
orchestra-1  |     cwd: '/home/node/xen-orchestra/packages/xo-server',
orchestra-1  |     failed: true,
orchestra-1  |     timedOut: false,
orchestra-1  |     isCanceled: false,
orchestra-1  |     killed: false
orchestra-1  |   }
orchestra-1  | }
```

**Comment by Ezka77** [comment]
I don't think theses error comes from xen-orchrestra or the alpine container: I don't have (all of) them on my machine. Do you have some lvm configured in your xen-orchestra ?

I have that one:
```
2024-10-21T07:03:40.880Z xo:mixins:hooks WARN start failure {
orchestra-1  |   error: Error: spawn xenstore-read ENOENT
orchestra-1  |       at Process.ChildProcess._handle.onexit (node:internal/child_process:284:19)
orchestra-1  |       at onErrorNT (node:internal/child_process:477:16)
orchestra-1  |       at processTicksAndRejections (node:internal/process/task_queues:82:21) {
orchestra-1  |     errno: -2,
orchestra-1  |     code: 'ENOENT',
orchestra-1  |     syscall: 'spawn xenstore-read',
orchestra-1  |     path: 'xenstore-read',
orchestra-1  |     spawnargs: [ 'vm' ],
orchestra-1  |     cmd: 'xenstore-read vm'
orchestra-1  |   }
```
But as this install is not an appliance I think it's ok-ish to see it.

The other ones you have are about LVM. To investigate, if you're running this image from docker compose you can start a shell in the container with:
```bash
docker compose run orchestra /bin/ash
```
But hard for me to help much more to debug your issue. All I can see here  it's about LVM :shrug:
